<script lang="ts">
	import KoalaLogo from '$lib/components/KoalaLogo.svelte';

	const snakeWorkflow = `name: Generate Contribution Snake

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk/svg-only@d8f6715049803e982ee5ff501b6b9b7d5deeb09b
        with:
          github_user_name: \${{ github.repository_owner }}
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}`;
</script>

<svelte:head>
	<title>Guide: GitHub Profile README and GitHub Actions Workflows | KoalaGitHub</title>
	<meta
		name="description"
		content="Step-by-step guide to creating a GitHub profile README, running daily GitHub Actions workflows, and adding animated contribution graphs."
	/>
	<link rel="canonical" href="https://github.koalastuff.net/guide" />
	<meta property="og:url" content="https://github.koalastuff.net/guide" />
</svelte:head>

<div class="guide-page container">
	<!-- Hero Section -->
	<div class="guide-hero">
		<KoalaLogo size={56} />
		<h1 class="guide-title">GitHub Profile README and Actions Workflow Guide</h1>
		<p class="guide-subtitle">
			Create the special profile repository, add visualizer Markdown, and safely run generators with
			GitHub Actions.
		</p>
	</div>

	<div class="guide-content">
		<!-- Step 1: Special Repository -->
		<section class="guide-card">
			<div class="card-step-badge">Step 1</div>
			<h2>Create your profile repository</h2>
			<p>
				GitHub displays a repository's <code>README.md</code> on your public profile when the public repository
				has the same name as your GitHub username.
			</p>

			<div class="info-box">
				<span class="box-icon">💡</span>
				<div>
					<strong>Example:</strong> For username <code>Shik3i</code>, the repository is located at
					<a href="https://github.com/Shik3i/Shik3i" target="_blank" rel="noopener noreferrer"
						>github.com/Shik3i/Shik3i ↗</a
					>.
				</div>
			</div>

			<ol class="step-list">
				<li>
					Go to <a href="https://github.com/new" target="_blank" rel="noopener noreferrer"
						>github.com/new ↗</a
					>.
				</li>
				<li>In the <strong>Repository name</strong> field, enter your exact GitHub username.</li>
				<li>Ensure the repository is set to <strong>Public</strong>.</li>
				<li>Select <strong>Add a README file</strong>.</li>
				<li>Click <strong>Create repository</strong>.</li>
				<li>
					Edit <code>README.md</code>; changes appear on your public profile after you commit them.
				</li>
			</ol>
		</section>

		<!-- Step 2: Instant Visualizers -->
		<section class="guide-card">
			<div class="card-step-badge">Step 2</div>
			<h2>Add an instant visualizer</h2>
			<p>
				Instant visualizers such as <strong>Kodama Bonsai Tree</strong>,
				<strong>GitHub Streak Stats</strong>, or <strong>Activity Graphs</strong> do not require a workflow
				in your repository. Their providers generate the image when GitHub requests its URL.
			</p>

			<ol class="step-list">
				<li>Enter your username in the <a href="/">KoalaGitHub Hub</a>.</li>
				<li>Select a supported theme.</li>
				<li>Click <strong>Copy Markdown</strong>.</li>
				<li>
					Edit your profile <code>README.md</code> on GitHub and paste the snippet where you want it to
					appear.
				</li>
				<li>Preview the profile and verify that the third-party image provider is available.</li>
			</ol>
		</section>

		<!-- Step 3: Self-Hosted GitHub Actions -->
		<section class="guide-card" id="generated-visualizers">
			<div class="card-step-badge">Step 3</div>
			<h2>Set up a generated visualizer</h2>
			<p>
				Generators such as the <strong>Contribution Grid Snake</strong> and
				<strong>Arcade Pac-Man Graph</strong> are not generated by KoalaGitHub and do not update dynamically
				when you change the username field. You must run the provided workflow in your own profile repository;
				it creates the SVG on a schedule and can also be started manually.
			</p>

			<h3>Add and verify the workflow</h3>
			<ol class="step-list">
				<li>
					Open your profile repository and create the workflow file named on the selected card, for
					example <code>.github/workflows/snake.yml</code>.
				</li>
				<li>
					Use <strong>Copy workflow (.yml)</strong> on that card and paste the code into the file.
				</li>
				<li>Commit it to the repository's default branch.</li>
				<li>
					Open the repository's <strong>Actions</strong> tab, select the workflow, and run
					<strong>Run workflow</strong>. Scheduled workflows run only from the default branch and
					may start later than their exact cron time.
				</li>
				<li>
					Wait for a successful run. Confirm that the generated file path matches the path in the
					Markdown snippet before adding it to <code>README.md</code>.
				</li>
			</ol>

			<div class="code-example-box">
				<div class="box-title">Example: .github/workflows/snake.yml</div>
				<pre class="yaml-code"><code>{snakeWorkflow}</code></pre>
			</div>

			<div class="warning-box">
				<span class="box-icon">🔐</span>
				<div>
					<strong>Permission and supply-chain note:</strong><br />
					The copied workflow grants only <code>contents: write</code>, which is required to publish
					the generated file. Actions are pinned to immutable commit SHAs. Repository or
					organization policy may still block writes; if so, review
					<strong>Settings → Actions → General → Workflow permissions</strong>. Never copy an
					unreviewed workflow or grant broader permissions just to make a run pass.
				</div>
			</div>
		</section>

		<!-- Step 4: Real-World Reference Repo -->
		<section class="guide-card reference-card">
			<div class="card-step-badge reference-badge">Live Reference</div>
			<h2>Real-world example repository</h2>
			<p>
				Want to see a fully configured working profile README in action? Check out the reference
				implementation:
			</p>

			<div class="reference-links">
				<a
					href="https://github.com/Shik3i/Shik3i"
					target="_blank"
					rel="noopener noreferrer"
					class="ref-link-btn"
				>
					<svg
						width="18"
						height="18"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
					>
						<path d="M3 7h5l2 2h11v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
						<path d="M3 7V5a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v2" />
					</svg>
					View Shik3i profile repository ↗
				</a>
				<a
					href="https://github.com/Shik3i/Shik3i/tree/main/.github/workflows"
					target="_blank"
					rel="noopener noreferrer"
					class="ref-link-btn secondary"
				>
					View live workflow files (.github/workflows) ↗
				</a>
			</div>
		</section>
	</div>
</div>

<style>
	.guide-page {
		padding: 2.5rem 1.25rem 4rem;
	}

	.guide-hero {
		display: flex;
		flex-direction: column;
		align-items: center;
		text-align: center;
		gap: 0.75rem;
		margin-bottom: 3rem;
	}

	.guide-title {
		font-size: 2.25rem;
		font-weight: 800;
		color: var(--text-main);
		letter-spacing: -0.03em;
	}

	.guide-subtitle {
		font-size: 1.1rem;
		color: var(--text-muted);
		max-width: 680px;
		line-height: 1.55;
	}

	.guide-content {
		display: flex;
		flex-direction: column;
		gap: 2rem;
		max-width: 860px;
		margin: 0 auto;
	}

	.guide-card {
		background-color: var(--bg-card);
		border: 1px solid var(--border-color);
		border-radius: var(--radius-lg);
		padding: 1.75rem;
		position: relative;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.card-step-badge {
		align-self: flex-start;
		font-size: 0.75rem;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		color: var(--brand-primary);
		background-color: var(--brand-light);
		padding: 0.2rem 0.6rem;
		border-radius: var(--radius-full);
	}

	.guide-card h2 {
		font-size: 1.35rem;
		font-weight: 700;
		color: var(--text-main);
	}

	.guide-card h3 {
		font-size: 1.1rem;
		font-weight: 600;
		color: var(--text-main);
		margin-top: 0.5rem;
	}

	.guide-card p {
		color: var(--text-muted);
		line-height: 1.6;
		font-size: 0.975rem;
	}

	.step-list {
		padding-left: 1.25rem;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		color: var(--text-main);
		font-size: 0.95rem;
		line-height: 1.5;
	}

	.info-box,
	.warning-box {
		display: flex;
		align-items: flex-start;
		gap: 0.75rem;
		padding: 1rem;
		border-radius: var(--radius-md);
		font-size: 0.9rem;
		line-height: 1.5;
	}

	.info-box {
		background-color: var(--koala-accent-bg);
		color: var(--text-main);
		border: 1px solid rgba(14, 165, 233, 0.3);
	}

	.warning-box {
		background-color: var(--warning-bg);
		color: var(--warning-text);
		border: 1px solid rgba(245, 158, 11, 0.3);
	}

	.box-icon {
		font-size: 1.25rem;
		line-height: 1;
	}

	.code-example-box {
		background-color: var(--bg-code);
		border-radius: var(--radius-md);
		padding: 1rem;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.box-title {
		font-size: 0.8rem;
		font-weight: 600;
		color: #94a3b8;
		text-transform: uppercase;
		letter-spacing: 0.03em;
	}

	.yaml-code {
		font-family: var(--font-mono);
		font-size: 0.825rem;
		color: #e2e8f0;
		overflow-x: auto;
		white-space: pre;
		margin: 0;
	}

	.reference-card {
		border-color: color-mix(in srgb, var(--brand-primary) 30%, transparent);
		background: linear-gradient(
			135deg,
			var(--bg-card) 0%,
			color-mix(in srgb, var(--brand-primary) 3%, transparent) 100%
		);
	}

	.reference-badge {
		background-color: color-mix(in srgb, var(--brand-primary) 15%, transparent);
		color: var(--brand-primary);
	}

	.reference-links {
		display: flex;
		gap: 0.75rem;
		flex-wrap: wrap;
		margin-top: 0.5rem;
	}

	.ref-link-btn {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.6rem 1.1rem;
		border-radius: var(--radius-md);
		font-weight: 600;
		font-size: 0.9rem;
		background-color: var(--brand-solid);
		color: var(--brand-on-solid);
		transition: background-color 0.15s ease;
	}

	.ref-link-btn:hover {
		background-color: var(--brand-solid-hover);
		color: var(--brand-on-solid);
	}

	.ref-link-btn.secondary {
		background-color: var(--bg-subtle);
		color: var(--text-main);
		border: 1px solid var(--border-color);
	}

	.ref-link-btn.secondary:hover {
		background-color: var(--border-color);
	}

	@media (max-width: 640px) {
		.guide-title {
			font-size: 1.75rem;
		}

		.guide-card {
			padding: 1.25rem;
		}
	}
</style>
